### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by KMastroluca** [KMastroluca/mvscanner#20]
Hey im testing POST methods and writing the functions to add new residents and timestamps. While testing these I saw that im getting the CORS error again in the Javascript console. 

How I fixed this before was I added specifically the address and port that my client dev server was running on, and specifically allowed PUT and POST. 

CORS really really doesnt like "Content-Type":"application/json" in this context. So even when you allow it with the wildcard like I assume .cors::default().allow_any_origin() does, it will allow GETs but not POSTs with data and shit. Anyway, im gonna alter it so I can get it working so I can continue to test, but Im just letting you know that Im gonna touch that part of the backend.

**Comment by PThorpe92** [comment]
I'm going to try running the back-end on my work laptop and then POST'ing a timestamp to it from my main machine, to see how it will work over the network. 

That is super weird because I have POST'd to it with data (obviously all the tests do that) but I"ll look into it

**Comment by KMastroluca** [comment]
I got it working. In prod, I imagine that we wont have this issue, this is an issue purely relarted to testing the client and server on different ports off localhost on a non-server machine.

**Comment by KMastroluca** [comment]
Youre just returning a string "Success"?

**Comment by PThorpe92** [comment]
join my zoom link is in the other comment chain for store-db

**Comment by PThorpe92** [comment]
I needed to know what you wanted returned and for what endpoint do you want a join?

**Comment by PThorpe92** [comment]
Ok I think this is fixed for now, but we have to remember in prod to switch it back
